### ISSUE TITLE
TypeError: render() got an unexpected keyword argument 'primary_features'

### ISSUE THREAD

**Issue by AlwaysLELE** [AronKovacs/g-style#3]
When I run the train.py file, I get the following error:
`Traceback (most recent call last):
  File "train.py", line 725, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.start_checkpoint)
  File "train.py", line 384, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, primary_features=True)
TypeError: render() got an unexpected keyword argument 'primary_features'
`
This prevents me from retraining the model.

I noticed that the author made changes to the render function and the Gaussian model. I am wondering if some issues were not resolved, which is causing the error.

Additionally, I found that the original project lacks the submodules folder (which seems to be required).

Could you help me solve this problem? I would really appreciate it!
@AronKovacs

**Comment by AlwaysLELE** [comment]
The problem was resolved and it was found that the local file was modified without synchronization to the remote file, resulting in an error
